### ISSUE TITLE
Remove tool-tips in Nautilus

### ISSUE THREAD

**Issue by WatchMkr** [system76/pop-gtk-theme#12]
```
Pop 17.04

pop-gtk-theme:
  Installed: 2.0.5.1
  Candidate: 2.0.5.1
 ```

Tool tips block content that a user may be attempting to navigate to and the additional information they provide isn't useful.
